version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    container_name: login_api
    restart: unless-stopped
    environment:
      - bye=bye
    volumes:
        # - ../django/config/secrets.json:/app/config/secrets.json
        # - ../django/django-local-efs:/var/www/django-local-efs
        - ../django:/app
    # ports:
    #   - 7000:7000

  nginx:
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/logs/:/var/log/nginx/
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - api
      - app

  app:
    build:
      context: ../
      dockerfile: Dockerfile.app
    container_name: login_app
    restart: always
    # volumes:
    #   - ../reactApp:/app
    ports:
      - 3000:3000
    depends_on:
      - api