version: "3.9"

services:
  api:
    image: dockerrexxzz/dj:latest
    environment:
      - bye=env
    # volumes:
    #     - ../django/secrets.json:/app/secrets.json
    #   - ../django/django-local-efs:/var/www/django-local-efs
    # ports:
    #   - 7000:7000  # if this commented out it means , expose port is available by default in docker swarm
    networks:
      - django
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == irwinrex
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
      resources:
          limits:
            cpus: '0.5'   
            memory: 0.5G
          reservations:
            cpus: '0.25'
            memory: 0.2G
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7000/home/']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  nginx:
    image: dockerrexxzz/djnginx:latest
    volumes:
      - /opt/logs/:/var/log/nginx/
    ports:
      - 80:80
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == irwinrex
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
          limits:
            cpus: '0.2'   
            memory: 0.3G
          reservations:
            cpus: '0.1'
            memory: 0.1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - api
    networks:
      - django
  app:
    image: dockerrexxzz/reactapp:latest
    ports:
      - 3000:3000
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == irwinrex
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '2'   
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - api
    networks:
      - django

networks:
  django:
    driver: overlay  # Use overlay network for Swarm deployment
