apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: sample-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7000
      nodePort: 30000
  type: NodePort
